name: taiyin_workspace
description: Workspace for the Taiyin Dart packages.
publish_to: none

environment:
  sdk: ^3.10.0

workspace:
  - packages/taiyin
  - packages/taiyin_bazi
  - packages/taiyin_ziwei

dev_dependencies:
  ffigen: ^20.1.1
