// coverage:ignore-file
// ignore_for_file: type=lint
// Generated by `dart run ffigen --config ffigen.yaml`. Do not edit.

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import
import 'dart:ffi' as ffi;

/// Generated bindings for the Taiyin C ABI.
class TaiyinBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  TaiyinBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  TaiyinBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int taiyin_get_c_abi_version() {
    return _taiyin_get_c_abi_version();
  }

  late final _taiyin_get_c_abi_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function()>>(
        'taiyin_get_c_abi_version',
      );
  late final _taiyin_get_c_abi_version = _taiyin_get_c_abi_versionPtr
      .asFunction<int Function()>();

  ffi.Pointer<ffi.Char> taiyin_get_library_version() {
    return _taiyin_get_library_version();
  }

  late final _taiyin_get_library_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'taiyin_get_library_version',
      );
  late final _taiyin_get_library_version = _taiyin_get_library_versionPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  int taiyin_get_capabilities() {
    return _taiyin_get_capabilities();
  }

  late final _taiyin_get_capabilitiesPtr =
      _lookup<ffi.NativeFunction<ffi.Uint64 Function()>>(
        'taiyin_get_capabilities',
      );
  late final _taiyin_get_capabilities = _taiyin_get_capabilitiesPtr
      .asFunction<int Function()>();

  ffi.Pointer<ffi.Char> taiyin_status_name(int status) {
    return _taiyin_status_name(status);
  }

  late final _taiyin_status_namePtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(taiyin_status)>
      >('taiyin_status_name');
  late final _taiyin_status_name = _taiyin_status_namePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(int)>();

  ffi.Pointer<ffi.Char> taiyin_status_message(int status) {
    return _taiyin_status_message(status);
  }

  late final _taiyin_status_messagePtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(taiyin_status)>
      >('taiyin_status_message');
  late final _taiyin_status_message = _taiyin_status_messagePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(int)>();

  int taiyin_context_create(
    ffi.Pointer<ffi.Pointer<taiyin_context>> out_context,
  ) {
    return _taiyin_context_create(out_context);
  }

  late final _taiyin_context_createPtr =
      _lookup<
        ffi.NativeFunction<
          taiyin_status Function(ffi.Pointer<ffi.Pointer<taiyin_context>>)
        >
      >('taiyin_context_create');
  late final _taiyin_context_create = _taiyin_context_createPtr
      .asFunction<int Function(ffi.Pointer<ffi.Pointer<taiyin_context>>)>();

  int taiyin_context_clone(
    ffi.Pointer<taiyin_context> source,
    ffi.Pointer<ffi.Pointer<taiyin_context>> out_context,
  ) {
    return _taiyin_context_clone(source, out_context);
  }

  late final _taiyin_context_clonePtr =
      _lookup<
        ffi.NativeFunction<
          taiyin_status Function(
            ffi.Pointer<taiyin_context>,
            ffi.Pointer<ffi.Pointer<taiyin_context>>,
          )
        >
      >('taiyin_context_clone');
  late final _taiyin_context_clone = _taiyin_context_clonePtr
      .asFunction<
        int Function(
          ffi.Pointer<taiyin_context>,
          ffi.Pointer<ffi.Pointer<taiyin_context>>,
        )
      >();

  void taiyin_context_destroy(ffi.Pointer<taiyin_context> context) {
    return _taiyin_context_destroy(context);
  }

  late final _taiyin_context_destroyPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<taiyin_context>)>
      >('taiyin_context_destroy');
  late final _taiyin_context_destroy = _taiyin_context_destroyPtr
      .asFunction<void Function(ffi.Pointer<taiyin_context>)>();

  int taiyin_calc_position_tt(
    ffi.Pointer<taiyin_context> context,
    int target_id,
    double jd_tt,
    int flags,
    ffi.Pointer<ffi.Double> out_position,
    ffi.Pointer<taiyin_ephemeris_diagnostic> diagnostic,
  ) {
    return _taiyin_calc_position_tt(
      context,
      target_id,
      jd_tt,
      flags,
      out_position,
      diagnostic,
    );
  }

  late final _taiyin_calc_position_ttPtr =
      _lookup<
        ffi.NativeFunction<
          taiyin_status Function(
            ffi.Pointer<taiyin_context>,
            ffi.Int32,
            ffi.Double,
            ffi.Uint32,
            ffi.Pointer<ffi.Double>,
            ffi.Pointer<taiyin_ephemeris_diagnostic>,
          )
        >
      >('taiyin_calc_position_tt');
  late final _taiyin_calc_position_tt = _taiyin_calc_position_ttPtr
      .asFunction<
        int Function(
          ffi.Pointer<taiyin_context>,
          int,
          double,
          int,
          ffi.Pointer<ffi.Double>,
          ffi.Pointer<taiyin_ephemeris_diagnostic>,
        )
      >();

  int taiyin_calc_position_ut(
    ffi.Pointer<taiyin_context> context,
    int target_id,
    double jd_ut,
    int flags,
    ffi.Pointer<ffi.Double> out_position,
    ffi.Pointer<taiyin_ephemeris_diagnostic> diagnostic,
  ) {
    return _taiyin_calc_position_ut(
      context,
      target_id,
      jd_ut,
      flags,
      out_position,
      diagnostic,
    );
  }

  late final _taiyin_calc_position_utPtr =
      _lookup<
        ffi.NativeFunction<
          taiyin_status Function(
            ffi.Pointer<taiyin_context>,
            ffi.Int32,
            ffi.Double,
            ffi.Uint32,
            ffi.Pointer<ffi.Double>,
            ffi.Pointer<taiyin_ephemeris_diagnostic>,
          )
        >
      >('taiyin_calc_position_ut');
  late final _taiyin_calc_position_ut = _taiyin_calc_position_utPtr
      .asFunction<
        int Function(
          ffi.Pointer<taiyin_context>,
          int,
          double,
          int,
          ffi.Pointer<ffi.Double>,
          ffi.Pointer<taiyin_ephemeris_diagnostic>,
        )
      >();

  void taiyin_runtime_config_init(ffi.Pointer<taiyin_runtime_config> config) {
    return _taiyin_runtime_config_init(config);
  }

  late final _taiyin_runtime_config_initPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<taiyin_runtime_config>)
        >
      >('taiyin_runtime_config_init');
  late final _taiyin_runtime_config_init = _taiyin_runtime_config_initPtr
      .asFunction<void Function(ffi.Pointer<taiyin_runtime_config>)>();

  int taiyin_runtime_initialize(ffi.Pointer<taiyin_runtime_config> config) {
    return _taiyin_runtime_initialize(config);
  }

  late final _taiyin_runtime_initializePtr =
      _lookup<
        ffi.NativeFunction<
          taiyin_status Function(ffi.Pointer<taiyin_runtime_config>)
        >
      >('taiyin_runtime_initialize');
  late final _taiyin_runtime_initialize = _taiyin_runtime_initializePtr
      .asFunction<int Function(ffi.Pointer<taiyin_runtime_config>)>();

  int taiyin_runtime_catalog_size() {
    return _taiyin_runtime_catalog_size();
  }

  late final _taiyin_runtime_catalog_sizePtr =
      _lookup<ffi.NativeFunction<ffi.Size Function()>>(
        'taiyin_runtime_catalog_size',
      );
  late final _taiyin_runtime_catalog_size = _taiyin_runtime_catalog_sizePtr
      .asFunction<int Function()>();
}

typedef __int8_t = ffi.SignedChar;
typedef Dart__int8_t = int;
typedef __uint8_t = ffi.UnsignedChar;
typedef Dart__uint8_t = int;
typedef __int16_t = ffi.Short;
typedef Dart__int16_t = int;
typedef __uint16_t = ffi.UnsignedShort;
typedef Dart__uint16_t = int;
typedef __int32_t = ffi.Int;
typedef Dart__int32_t = int;
typedef __uint32_t = ffi.UnsignedInt;
typedef Dart__uint32_t = int;
typedef __int64_t = ffi.LongLong;
typedef Dart__int64_t = int;
typedef __uint64_t = ffi.UnsignedLongLong;
typedef Dart__uint64_t = int;
typedef __darwin_intptr_t = ffi.Long;
typedef Dart__darwin_intptr_t = int;
typedef __darwin_natural_t = ffi.UnsignedInt;
typedef Dart__darwin_natural_t = int;
typedef __darwin_ct_rune_t = ffi.Int;
typedef Dart__darwin_ct_rune_t = int;

final class __mbstate_t extends ffi.Union {
  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> __mbstate8;

  @ffi.LongLong()
  external int _mbstateL;
}

typedef __darwin_mbstate_t = __mbstate_t;
typedef __darwin_ptrdiff_t = ffi.Long;
typedef Dart__darwin_ptrdiff_t = int;
typedef __darwin_size_t = ffi.UnsignedLong;
typedef Dart__darwin_size_t = int;
typedef __builtin_va_list = ffi.Pointer<ffi.Char>;
typedef __darwin_va_list = __builtin_va_list;
typedef __darwin_wchar_t = ffi.Int;
typedef Dart__darwin_wchar_t = int;
typedef __darwin_rune_t = __darwin_wchar_t;
typedef __darwin_wint_t = ffi.Int;
typedef Dart__darwin_wint_t = int;
typedef __darwin_clock_t = ffi.UnsignedLong;
typedef Dart__darwin_clock_t = int;
typedef __darwin_socklen_t = __uint32_t;
typedef __darwin_ssize_t = ffi.Long;
typedef Dart__darwin_ssize_t = int;
typedef __darwin_time_t = ffi.Long;
typedef Dart__darwin_time_t = int;
typedef u_int8_t = ffi.UnsignedChar;
typedef Dartu_int8_t = int;
typedef u_int16_t = ffi.UnsignedShort;
typedef Dartu_int16_t = int;
typedef u_int32_t = ffi.UnsignedInt;
typedef Dartu_int32_t = int;
typedef u_int64_t = ffi.UnsignedLongLong;
typedef Dartu_int64_t = int;
typedef register_t = ffi.Int64;
typedef Dartregister_t = int;
typedef user_addr_t = u_int64_t;
typedef user_size_t = u_int64_t;
typedef user_ssize_t = ffi.Int64;
typedef Dartuser_ssize_t = int;
typedef user_long_t = ffi.Int64;
typedef Dartuser_long_t = int;
typedef user_ulong_t = u_int64_t;
typedef user_time_t = ffi.Int64;
typedef Dartuser_time_t = int;
typedef user_off_t = ffi.Int64;
typedef Dartuser_off_t = int;
typedef user_addr_ut = user_addr_t;
typedef user_size_ut = user_size_t;
typedef user64_addr_t = __uint64_t;
typedef user64_size_t = __uint64_t;
typedef user64_ssize_t = __int64_t;
typedef user64_long_t = __int64_t;
typedef user64_ulong_t = __uint64_t;
typedef user64_time_t = __int64_t;
typedef user64_off_t = __int64_t;
typedef user32_addr_t = __uint32_t;
typedef user32_size_t = __uint32_t;
typedef user32_ssize_t = __int32_t;
typedef user32_long_t = __int32_t;
typedef user32_ulong_t = __uint32_t;
typedef user32_time_t = __int32_t;
typedef user32_off_t = __int64_t;
typedef syscall_arg_t = u_int64_t;
typedef int_least8_t = ffi.Int8;
typedef Dartint_least8_t = int;
typedef int_least16_t = ffi.Int16;
typedef Dartint_least16_t = int;
typedef int_least32_t = ffi.Int32;
typedef Dartint_least32_t = int;
typedef int_least64_t = ffi.Int64;
typedef Dartint_least64_t = int;
typedef uint_least8_t = ffi.Uint8;
typedef Dartuint_least8_t = int;
typedef uint_least16_t = ffi.Uint16;
typedef Dartuint_least16_t = int;
typedef uint_least32_t = ffi.Uint32;
typedef Dartuint_least32_t = int;
typedef uint_least64_t = ffi.Uint64;
typedef Dartuint_least64_t = int;
typedef int_fast8_t = ffi.Int8;
typedef Dartint_fast8_t = int;
typedef int_fast16_t = ffi.Int16;
typedef Dartint_fast16_t = int;
typedef int_fast32_t = ffi.Int32;
typedef Dartint_fast32_t = int;
typedef int_fast64_t = ffi.Int64;
typedef Dartint_fast64_t = int;
typedef uint_fast8_t = ffi.Uint8;
typedef Dartuint_fast8_t = int;
typedef uint_fast16_t = ffi.Uint16;
typedef Dartuint_fast16_t = int;
typedef uint_fast32_t = ffi.Uint32;
typedef Dartuint_fast32_t = int;
typedef uint_fast64_t = ffi.Uint64;
typedef Dartuint_fast64_t = int;
typedef intmax_t = ffi.Long;
typedef Dartintmax_t = int;
typedef uintmax_t = ffi.UnsignedLong;
typedef Dartuintmax_t = int;

sealed class taiyin_capability {
  static const TAIYIN_CAPABILITY_RUNTIME = 1;
  static const TAIYIN_CAPABILITY_TIME = 2;
  static const TAIYIN_CAPABILITY_POSITION = 4;
  static const TAIYIN_CAPABILITY_STAR = 8;
  static const TAIYIN_CAPABILITY_VISIBILITY = 16;
  static const TAIYIN_CAPABILITY_PHENOMENA = 32;
  static const TAIYIN_CAPABILITY_EVENTS = 64;
  static const TAIYIN_CAPABILITY_ECLIPSE = 128;
  static const TAIYIN_CAPABILITY_OCCULTATION = 256;
  static const TAIYIN_CAPABILITY_HELIACAL = 512;
  static const TAIYIN_CAPABILITY_ASTROLOGY = 1024;
  static const TAIYIN_CAPABILITY_CUSTOM_TARGETS = 2048;
  static const TAIYIN_CAPABILITY_CUSTOM_AYANAMSHA = 4096;
  static const TAIYIN_CAPABILITY_CUSTOM_HOUSES = 8192;
}

typedef taiyin_status = ffi.Int32;
typedef Darttaiyin_status = int;
typedef taiyin_bool = ffi.Uint8;
typedef Darttaiyin_bool = int;

sealed class taiyin_status_code {
  static const TAIYIN_STATUS_OK = 0;
  static const TAIYIN_ERROR_INVALID_ARGUMENT = -1;
  static const TAIYIN_ERROR_OUT_OF_MEMORY = -2;
  static const TAIYIN_ERROR_INTERNAL = -3;
  static const TAIYIN_ERROR_UNSUPPORTED = -4;
  static const TAIYIN_EPHEMERIS_ERROR_NO_ROUTE = -1001;
  static const TAIYIN_EPHEMERIS_ERROR_COVERAGE_GAP = -1002;
  static const TAIYIN_EPHEMERIS_ERROR_LOAD_FAILED = -1003;
  static const TAIYIN_EPHEMERIS_ERROR_EVAL_FAILED = -1004;
  static const TAIYIN_EPHEMERIS_ERROR_COMPOSITE_MISSING_COMPONENT = -1010;
  static const TAIYIN_EPHEMERIS_ERROR_COMPOSITE_COVERAGE_GAP = -1011;
  static const TAIYIN_EPHEMERIS_ERROR_COMPOSITE_METHOD_MISMATCH = -1012;
  static const TAIYIN_FILE_ERROR_NOT_FOUND = -2001;
  static const TAIYIN_FILE_ERROR_BAD_FORMAT = -2002;
  static const TAIYIN_FILE_ERROR_UNSUPPORTED_FORMAT = -2003;
  static const TAIYIN_FILE_ERROR_DISCOVERY_FAILED = -2004;
  static const TAIYIN_TIME_ERROR_EOP_OUT_OF_RANGE = -3001;
  static const TAIYIN_TIME_ERROR_LEAP_SECOND_UNAVAILABLE = -3002;
  static const TAIYIN_EVENT_ERROR_NOT_FOUND = -5001;
  static const TAIYIN_RUNTIME_ERROR_NOT_INITIALIZED = -6001;
  static const TAIYIN_RUNTIME_ERROR_CACHE_INSERT_FAILED = -6002;
  static const TAIYIN_RUNTIME_ERROR_REGISTRY_FAILED = -6003;
}

sealed class taiyin_status_category {
  static const TAIYIN_STATUS_CATEGORY_OK = 0;
  static const TAIYIN_STATUS_CATEGORY_GENERIC = 1;
  static const TAIYIN_STATUS_CATEGORY_EPHEMERIS = 10;
  static const TAIYIN_STATUS_CATEGORY_FILE = 20;
  static const TAIYIN_STATUS_CATEGORY_TIME = 30;
  static const TAIYIN_STATUS_CATEGORY_OBSERVER = 40;
  static const TAIYIN_STATUS_CATEGORY_EVENT = 50;
  static const TAIYIN_STATUS_CATEGORY_RUNTIME = 60;
  static const TAIYIN_STATUS_CATEGORY_UNKNOWN = 999;
}

final class taiyin_vector3 extends ffi.Struct {
  @ffi.Double()
  external double x;

  @ffi.Double()
  external double y;

  @ffi.Double()
  external double z;
}

final class taiyin_cartesian_state extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  external taiyin_vector3 position_au;

  external taiyin_vector3 velocity_au_per_day;

  external taiyin_vector3 acceleration_au_per_day2;
}

final class taiyin_ephemeris_diagnostic extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @taiyin_status()
  external int status;

  @ffi.Int32()
  external int target_id;

  @ffi.Int32()
  external int center_id;

  @ffi.Int32()
  external int frame;

  @ffi.Double()
  external double jd_tdb;

  @ffi.Int32()
  external int candidate_count;

  @ffi.Int32()
  external int attempted_method_id;

  @ffi.Double()
  external double nearest_coverage_start;

  @ffi.Double()
  external double nearest_coverage_end;

  @ffi.Int32()
  external int component_target_id;

  @ffi.Int32()
  external int component_center_id;

  @ffi.Int32()
  external int component_method_id;

  @ffi.Uint8()
  external int time_scale_route;

  @ffi.Uint8()
  external int time_scale_fallback_reason;

  @ffi.Uint8()
  external int time_scale_flags;

  @ffi.Uint8()
  external int reserved0;

  @ffi.Double()
  external double tai_minus_utc_seconds;

  @ffi.Double()
  external double dut1_seconds;

  @ffi.Double()
  external double delta_t_seconds;
}

final class taiyin_context extends ffi.Opaque {}

sealed class taiyin_time_scale_policy {
  static const TAIYIN_TIME_SCALE_AUTO = 0;
  static const TAIYIN_TIME_SCALE_PRECISE = 1;
  static const TAIYIN_TIME_SCALE_ESTIMATED = 2;
}

sealed class taiyin_atmosphere_policy_flags {
  static const TAIYIN_ATMOSPHERE_ALLOW_STANDARD_FALLBACK = 1;
}

sealed class taiyin_model_selection_id {
  static const TAIYIN_MODEL_DEFAULT = -1;
}

sealed class taiyin_precession_model_id {
  static const TAIYIN_PRECESSION_VONDRAK_2011 = 0;
  static const TAIYIN_PRECESSION_IAU_2006 = 1;
  static const TAIYIN_PRECESSION_IAU_1976 = 2;
  static const TAIYIN_PRECESSION_NEWCOMB_1895 = 3;
}

sealed class taiyin_nutation_model_id {
  static const TAIYIN_NUTATION_IAU_2000B = 0;
  static const TAIYIN_NUTATION_IAU_2000A = 1;
}

sealed class taiyin_tdb_model_id {
  static const TAIYIN_TDB_FAST_PERIODIC = 0;
  static const TAIYIN_TDB_SOFA_FULL = 1;
}

sealed class taiyin_frame_route_id {
  static const TAIYIN_FRAME_ROUTE_EQUINOX = 0;
  static const TAIYIN_FRAME_ROUTE_CIRS = 1;
}

sealed class taiyin_delta_t_model_id {
  static const TAIYIN_DELTA_T_ESTIMATED_DEFAULT = 0;
}

sealed class taiyin_ephemeris_family_id {
  static const TAIYIN_EPHEMERIS_FAMILY_UNKNOWN = 0;
  static const TAIYIN_EPHEMERIS_FAMILY_DE431 = 431;
  static const TAIYIN_EPHEMERIS_FAMILY_DE441 = 441;
}

sealed class taiyin_refraction_model_id {
  static const TAIYIN_REFRACTION_BENNETT = 0;
  static const TAIYIN_REFRACTION_SKYFIELD = 1;
  static const TAIYIN_REFRACTION_HYBRID = 2;
  static const TAIYIN_REFRACTION_AUER_STANDISH = 3;
  static const TAIYIN_REFRACTION_SOFA = 4;
}

sealed class taiyin_heliacal_visibility_model_id {
  static const TAIYIN_HELIACAL_VISIBILITY_BELOKRYLOV_2011 = 0;
  static const TAIYIN_HELIACAL_VISIBILITY_SCHAEFER_1993 = 1;
}

sealed class taiyin_aberration_model_id {
  static const TAIYIN_ABERRATION_ANNUAL_RELATIVISTIC = 0;
}

sealed class taiyin_apparent_flags {
  static const TAIYIN_APPARENT_FLAG_LIGHT_TIME = 1;
  static const TAIYIN_APPARENT_FLAG_SPHERICAL = 4;
  static const TAIYIN_APPARENT_FLAG_ABERRATION = 8;
  static const TAIYIN_APPARENT_FLAG_DEFLECTION = 16;
  static const TAIYIN_APPARENT_FLAG_VELOCITY = 32;
  static const TAIYIN_APPARENT_FLAG_ACCELERATION = 64;
  static const TAIYIN_APPARENT_FLAG_SHAPIRO_DELAY = 128;
}

sealed class taiyin_deflection_model_id {
  static const TAIYIN_DEFLECTION_ERFA = 0;
  static const TAIYIN_DEFLECTION_SOLAR_DISK = 1;
}

sealed class taiyin_eclipse_shadow_model_id {
  static const TAIYIN_ECLIPSE_SHADOW_NASA_DANJON = 0;
  static const TAIYIN_ECLIPSE_SHADOW_CHAUVENET = 1;
  static const TAIYIN_ECLIPSE_SHADOW_GEOMETRIC = 2;
  static const TAIYIN_ECLIPSE_SHADOW_RAW_DANJON = 3;
}

sealed class taiyin_eclipse_moon_radius_model_id {
  static const TAIYIN_ECLIPSE_MOON_ALMANAC = 0;
  static const TAIYIN_ECLIPSE_MOON_MEAN = 1;
}

sealed class taiyin_body_id {
  static const TAIYIN_BODY_SSB = 0;
  static const TAIYIN_BODY_MERCURY_BARYCENTER = 1;
  static const TAIYIN_BODY_VENUS_BARYCENTER = 2;
  static const TAIYIN_BODY_EMB = 3;
  static const TAIYIN_BODY_MARS_BARYCENTER = 4;
  static const TAIYIN_BODY_JUPITER_BARYCENTER = 5;
  static const TAIYIN_BODY_SATURN_BARYCENTER = 6;
  static const TAIYIN_BODY_URANUS_BARYCENTER = 7;
  static const TAIYIN_BODY_NEPTUNE_BARYCENTER = 8;
  static const TAIYIN_BODY_PLUTO_BARYCENTER = 9;
  static const TAIYIN_BODY_SUN = 10;
  static const TAIYIN_BODY_MERCURY = 199;
  static const TAIYIN_BODY_VENUS = 299;
  static const TAIYIN_BODY_MOON = 301;
  static const TAIYIN_BODY_EARTH = 399;
  static const TAIYIN_BODY_MARS = 499;
  static const TAIYIN_BODY_JUPITER = 599;
  static const TAIYIN_BODY_SATURN = 699;
  static const TAIYIN_BODY_URANUS = 799;
  static const TAIYIN_BODY_NEPTUNE = 899;
  static const TAIYIN_BODY_PLUTO = 999;
}

sealed class taiyin_position_flags {
  static const TAIYIN_POSITION_SPEED = 1;
  static const TAIYIN_POSITION_XYZ = 2;
  static const TAIYIN_POSITION_EQUATORIAL = 4;
  static const TAIYIN_POSITION_RADIANS = 8;
  static const TAIYIN_POSITION_TRUEPOS = 16;
  static const TAIYIN_POSITION_NO_ABERR = 32;
  static const TAIYIN_POSITION_NO_GDEFL = 64;
  static const TAIYIN_POSITION_ASTROMETRIC = 128;
  static const TAIYIN_POSITION_NONUT = 256;
  static const TAIYIN_POSITION_TOPOCENTRIC = 512;
  static const TAIYIN_POSITION_ALLOW_BARYCENTER_APPROX = 1024;
}

sealed class taiyin_apparent_frame_id {
  static const TAIYIN_FRAME_ICRF = 0;
  static const TAIYIN_FRAME_TRUE_EQUATOR_OF_DATE = 1;
  static const TAIYIN_FRAME_TRUE_ECLIPTIC_OF_DATE = 2;
  static const TAIYIN_FRAME_J2000_MEAN_EQUATOR = 3;
  static const TAIYIN_FRAME_J2000_ECLIPTIC = 4;
  static const TAIYIN_FRAME_MEAN_EQUATOR_OF_DATE = 5;
  static const TAIYIN_FRAME_MEAN_ECLIPTIC_OF_DATE = 6;
  static const TAIYIN_FRAME_CIRS = 7;
}

typedef taiyin_native_position_evaluator_fnFunction =
    taiyin_status Function(
      ffi.Pointer<taiyin_context> context,
      ffi.Int32 target_id,
      ffi.Double jd_tdb,
      ffi.Double jd_tt,
      ffi.Uint32 flags,
      ffi.Pointer<ffi.Double> out_position,
      ffi.Pointer<taiyin_ephemeris_diagnostic> diagnostic,
      ffi.Pointer<ffi.Void> user_data,
    );
typedef Darttaiyin_native_position_evaluator_fnFunction =
    Darttaiyin_status Function(
      ffi.Pointer<taiyin_context> context,
      int target_id,
      double jd_tdb,
      double jd_tt,
      int flags,
      ffi.Pointer<ffi.Double> out_position,
      ffi.Pointer<taiyin_ephemeris_diagnostic> diagnostic,
      ffi.Pointer<ffi.Void> user_data,
    );
typedef taiyin_native_position_evaluator_fn =
    ffi.Pointer<
      ffi.NativeFunction<taiyin_native_position_evaluator_fnFunction>
    >;
typedef taiyin_native_state_evaluator_fnFunction =
    taiyin_status Function(
      ffi.Pointer<taiyin_context> context,
      ffi.Int32 target_id,
      ffi.Double jd_tdb,
      ffi.Double jd_tt,
      ffi.Uint32 flags,
      ffi.Pointer<taiyin_cartesian_state> out_state,
      ffi.Pointer<taiyin_ephemeris_diagnostic> diagnostic,
      ffi.Pointer<ffi.Void> user_data,
    );
typedef Darttaiyin_native_state_evaluator_fnFunction =
    Darttaiyin_status Function(
      ffi.Pointer<taiyin_context> context,
      int target_id,
      double jd_tdb,
      double jd_tt,
      int flags,
      ffi.Pointer<taiyin_cartesian_state> out_state,
      ffi.Pointer<taiyin_ephemeris_diagnostic> diagnostic,
      ffi.Pointer<ffi.Void> user_data,
    );
typedef taiyin_native_state_evaluator_fn =
    ffi.Pointer<ffi.NativeFunction<taiyin_native_state_evaluator_fnFunction>>;

final class taiyin_runtime_config extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int api_version;

  @ffi.Size()
  external int segment_cache_max_entries;

  external ffi.Pointer<ffi.Pointer<ffi.Char>> source_paths;

  @ffi.Size()
  external int source_path_count;

  external ffi.Pointer<ffi.Char> data_root;

  external ffi.Pointer<ffi.Char> eop_path;

  external ffi.Pointer<ffi.Char> lunar_limb_path;

  @taiyin_bool()
  external int load_packaged_data;

  @taiyin_bool()
  external int load_builtin_eop;

  @taiyin_bool()
  external int strict_discovery;

  @ffi.Uint8()
  external int reserved0;
}
