const int taiyinSupportedAbiVersion = 1;
const int taiyinSplitTimeCapability = 1 << 14;

/// Symbols added while ABI 1 was still in development and required by the
/// high-level APIs exposed by this package.
const Set<String> taiyinRequiredAbi1Symbols = {
  'taiyin_get_library_codename',
  'taiyin_format_ephemeris_diagnostic',
  'taiyin_register_native_position_evaluator',
  'taiyin_unregister_native_position_evaluator',
  'taiyin_clear_native_position_evaluators',
  'taiyin_runtime_add_source_path',
  'taiyin_runtime_load_eop_table',
  'taiyin_runtime_load_builtin_eop_table',
  'taiyin_runtime_clear_eop_table',
  'taiyin_runtime_has_eop_table',
  'taiyin_runtime_load_lunar_limb_model',
  'taiyin_runtime_clear_lunar_limb_model',
  'taiyin_runtime_has_lunar_limb_model',
  'taiyin_runtime_clear_ephemeris_cache',
  'taiyin_runtime_cache_entry_count',
  'taiyin_body_osculating_orbit_init',
  'taiyin_body_orbit_reference_points_init',
  'taiyin_body_apsis_search_result_init',
  'taiyin_body_node_search_result_init',
  'taiyin_calc_body_osculating_orbit_tt',
  'taiyin_calc_body_osculating_orbit_ut',
  'taiyin_calc_body_orbit_reference_points_tt',
  'taiyin_calc_body_orbit_reference_points_ut',
  'taiyin_search_next_body_apsis_tt',
  'taiyin_search_next_body_apsis_ut',
  'taiyin_search_next_body_plane_node_tt',
  'taiyin_search_next_body_plane_node_ut',
  'taiyin_body_phenomena_init',
  'taiyin_calc_body_phenomena_tt',
  'taiyin_calc_body_phenomena_ut',
  'taiyin_equation_of_time_result_init',
  'taiyin_calc_equation_of_time_ut',
  'taiyin_calc_equation_of_time_tt',
  'taiyin_local_mean_to_apparent_solar_time',
  'taiyin_local_apparent_to_mean_solar_time',
  'taiyin_star_catalog_add_tsc1',
  'taiyin_star_catalog_add_tsc1_memory',
  'taiyin_star_catalog_add_tsf1',
  'taiyin_star_catalog_clear',
  'taiyin_star_catalog_count',
  'taiyin_star_find_magnitude',
  'taiyin_calc_star_position_tdb',
  'taiyin_calc_star_position_tt',
  'taiyin_calc_star_position_ut',
  'taiyin_calc_star_position_ut_delta_t',
  'taiyin_calc_star_positions_tdb',
  'taiyin_calc_star_positions_tt',
  'taiyin_calc_star_positions_ut',
  'taiyin_calc_star_positions_ut_delta_t',
  'taiyin_calc_observed_star_ut',
  'taiyin_calc_observed_stars_ut',
  'taiyin_sidereal_position_init',
  'taiyin_sidereal_coordinates_init',
  'taiyin_house_result_init',
  'taiyin_house_position_result_init',
  'taiyin_lunar_node_position_init',
  'taiyin_lunar_apsis_position_init',
  'taiyin_calc_ayanamsha_tt',
  'taiyin_calc_sidereal_position_tt',
  'taiyin_calc_sidereal_position_ut',
  'taiyin_calc_sidereal_coordinates_tt',
  'taiyin_calc_sidereal_coordinates_ut',
  'taiyin_calc_houses_from_armc',
  'taiyin_calc_houses_ut',
  'taiyin_calc_houses_tt',
  'taiyin_calc_house_position_from_longitude',
  'taiyin_has_house_system_model',
  'taiyin_has_ayanamsha_model',
  'taiyin_register_ayanamsha_model',
  'taiyin_register_house_system_model',
  'taiyin_register_ayanamsha_model_with_token',
  'taiyin_register_house_system_model_with_token',
  'taiyin_unregister_ayanamsha_model',
  'taiyin_unregister_house_system_model',
  'taiyin_unregister_ayanamsha_model_with_token',
  'taiyin_unregister_house_system_model_with_token',
  'taiyin_clear_ayanamsha_models',
  'taiyin_clear_house_system_models',
  'taiyin_register_builtin_astrology_targets',
  'taiyin_calc_lunar_true_node_tt',
  'taiyin_calc_lunar_true_node_ut',
  'taiyin_calc_lunar_mean_node_tt',
  'taiyin_calc_lunar_mean_node_ut',
  'taiyin_calc_lunar_mean_apogee_tt',
  'taiyin_calc_lunar_mean_apogee_ut',
  'taiyin_calc_lunar_osculating_apogee_tt',
  'taiyin_calc_lunar_osculating_apogee_ut',
  'taiyin_calc_lunar_fitted_apogee_tt',
  'taiyin_calc_lunar_fitted_apogee_ut',
  'taiyin_visibility_event_result_init',
  'taiyin_solar_rise_set_fast_result_init',
  'taiyin_solar_transit_fast_result_init',
  'taiyin_search_moon_rise_set_ut',
  'taiyin_search_moon_rise_set_at_horizon_ut',
  'taiyin_search_moon_transit_ut',
  'taiyin_search_planet_rise_set_ut',
  'taiyin_search_planet_rise_set_at_horizon_ut',
  'taiyin_search_planet_transit_ut',
  'taiyin_search_solar_rise_set_ut',
  'taiyin_search_solar_rise_set_at_horizon_ut',
  'taiyin_search_solar_twilight_ut',
  'taiyin_search_solar_transit_ut',
  'taiyin_compute_solar_rise_set_fast_tt',
  'taiyin_compute_solar_transit_fast_tt',
  'taiyin_search_star_rise_set_ut',
  'taiyin_search_star_rise_set_at_horizon_ut',
  'taiyin_search_star_transit_ut',
  'taiyin_heliacal_visibility_conditions_init',
  'taiyin_heliacal_visibility_result_init',
  'taiyin_heliacal_visibility_search_result_init',
  'taiyin_calc_body_heliacal_visibility_ut',
  'taiyin_calc_star_heliacal_visibility_ut',
  'taiyin_search_next_body_heliacal_visibility_ut',
  'taiyin_search_next_star_heliacal_visibility_ut',
  'taiyin_greatest_elongation_result_init',
  'taiyin_angular_separation_result_init',
  'taiyin_solar_transit_result_init',
  'taiyin_local_solar_transit_result_init',
  'taiyin_recommended_longitude_search_step_days',
  'taiyin_recommended_aspect_search_step_days',
  'taiyin_search_solar_longitude_ut',
  'taiyin_search_solar_longitude_tt',
  'taiyin_search_moon_longitude_ut',
  'taiyin_search_moon_longitude_tt',
  'taiyin_search_body_longitude_crossings_ut',
  'taiyin_search_body_longitude_crossings_tt',
  'taiyin_search_body_longitude_stations_ut',
  'taiyin_search_body_longitude_stations_tt',
  'taiyin_search_body_aspect_crossings_ut',
  'taiyin_search_body_aspect_crossings_tt',
  'taiyin_search_body_exact_aspects_ut',
  'taiyin_search_body_exact_aspects_tt',
  'taiyin_search_greatest_elongation_ut',
  'taiyin_search_minimum_angular_separation_ut',
  'taiyin_search_minimum_angular_separation_tt',
  'taiyin_search_next_solar_transit_ut',
  'taiyin_compute_local_solar_transit_ut',
  'taiyin_search_next_local_solar_transit_ut',
  'taiyin_search_lunar_phase_crossings_ut',
  'taiyin_search_lunar_phase_crossings_tt',
  'taiyin_lunar_occultation_result_init',
  'taiyin_lunar_occultation_local_visibility_init',
  'taiyin_lunar_occultation_where_result_init',
  'taiyin_search_next_geocentric_lunar_star_occultation_ut',
  'taiyin_search_next_local_lunar_star_occultation_ut',
  'taiyin_search_next_geocentric_lunar_body_occultation_ut',
  'taiyin_search_next_geocentric_lunar_body_occultation_with_radius_ut',
  'taiyin_search_next_local_lunar_body_occultation_ut',
  'taiyin_search_next_local_lunar_body_occultation_with_radius_ut',
  'taiyin_compute_lunar_star_occultation_local_visibility_ut',
  'taiyin_compute_lunar_body_occultation_local_visibility_ut',
  'taiyin_compute_lunar_star_occultation_where_ut',
  'taiyin_compute_lunar_body_occultation_where_ut',
  'taiyin_compute_lunar_body_occultation_where_with_radius_ut',
  'taiyin_lunar_eclipse_result_tt_init',
  'taiyin_lunar_eclipse_result_ut_init',
  'taiyin_local_lunar_eclipse_result_tt_init',
  'taiyin_local_lunar_eclipse_result_ut_init',
  'taiyin_solve_lunar_eclipse_at_tt',
  'taiyin_solve_lunar_eclipse_at_ut',
  'taiyin_search_next_lunar_eclipse_tt',
  'taiyin_search_next_lunar_eclipse_ut',
  'taiyin_search_lunar_eclipses_tt',
  'taiyin_search_lunar_eclipses_ut',
  'taiyin_compute_local_lunar_eclipse_visibility_tt',
  'taiyin_compute_local_lunar_eclipse_visibility_ut',
  'taiyin_search_next_local_lunar_eclipse_tt',
  'taiyin_search_next_local_lunar_eclipse_ut',
  'taiyin_solar_eclipse_result_tt_init',
  'taiyin_solar_eclipse_result_ut_init',
  'taiyin_local_solar_eclipse_result_tt_init',
  'taiyin_local_solar_eclipse_result_ut_init',
  'taiyin_local_solar_eclipse_circumstances_tt_init',
  'taiyin_local_solar_eclipse_circumstances_ut_init',
  'taiyin_local_solar_eclipse_boundary_init',
  'taiyin_solar_besselian_elements_init',
  'taiyin_solar_besselian_polynomial_init',
  'taiyin_solar_eclipse_route_row_init',
  'taiyin_solar_eclipse_route_product_summary_init',
  'taiyin_solve_solar_eclipse_at_tt',
  'taiyin_solve_solar_eclipse_at_ut',
  'taiyin_search_next_solar_eclipse_tt',
  'taiyin_search_next_solar_eclipse_ut',
  'taiyin_search_solar_eclipses_tt',
  'taiyin_search_solar_eclipses_ut',
  'taiyin_solve_local_solar_eclipse_at_tt',
  'taiyin_solve_local_solar_eclipse_at_ut',
  'taiyin_search_next_local_solar_eclipse_tt',
  'taiyin_search_next_local_solar_eclipse_ut',
  'taiyin_compute_local_solar_circumstances_tt',
  'taiyin_compute_local_solar_circumstances_ut',
  'taiyin_compute_solar_besselian_elements_tt',
  'taiyin_compute_solar_besselian_polynomial_tt',
  'taiyin_evaluate_solar_besselian_polynomial',
  'taiyin_compute_solar_eclipse_route_row_tt',
  'taiyin_compute_solar_eclipse_route_row_ut',
  'taiyin_compute_solar_eclipse_route_tt',
  'taiyin_compute_solar_eclipse_route_ut',
  'taiyin_compute_solar_eclipse_route_curves_tt',
  'taiyin_compute_solar_eclipse_route_curves_ut',
  'taiyin_compute_solar_eclipse_route_product_tt',
  'taiyin_compute_solar_eclipse_route_product_ut',
  'taiyin_compute_solar_eclipse_route_map_product_tt',
  'taiyin_compute_solar_eclipse_route_map_product_ut',
  'taiyin_compute_local_solar_eclipse_boundary_tt',
  'taiyin_compute_local_solar_eclipse_boundary_ut',
};

/// Validates the native metadata available before any optional symbol lookup.
///
/// This stays independent of generated bindings so compatibility behavior can
/// be tested without loading a platform-specific dynamic library.
///
/// The Dart package exposes its split-date time service as a required part of
/// every `TaiyinContext`, so it intentionally rejects otherwise-compatible
/// intermediate ABI-1 builds that predate the capability marker.
void validateTaiyinNativeCompatibility({
  required int abiVersion,
  required int capabilities,
}) {
  if (abiVersion != taiyinSupportedAbiVersion) {
    throw StateError(
      'Unsupported Taiyin C ABI $abiVersion; '
      'this package supports ABI $taiyinSupportedAbiVersion.',
    );
  }
  if ((capabilities & taiyinSplitTimeCapability) == 0) {
    throw StateError(
      'The loaded Taiyin library does not provide the split-time capability '
      'required by this package.',
    );
  }
}

/// Rejects intermediate ABI-1 builds before generated bindings lazily look up
/// a missing symbol.
void validateTaiyinRequiredSymbols({
  required bool Function(String symbol) providesSymbol,
  Set<String> requiredSymbols = taiyinRequiredAbi1Symbols,
}) {
  final missing = [
    for (final symbol in requiredSymbols)
      if (!providesSymbol(symbol)) symbol,
  ];
  if (missing.isNotEmpty) {
    throw StateError(
      'The loaded Taiyin ABI-1 library is missing symbols required by this '
      'package: ${missing.join(', ')}. Rebuild or update the native library.',
    );
  }
}
