const int taiyinSupportedAbiVersion = 9;
const int taiyinSplitTimeCapability = 1 << 14;
const int taiyinChineseCalendarCapability = 1 << 15;
const int taiyinBaziCapability = 1 << 16;
const int taiyinGanzhiCalendarCapability = 1 << 17;
const int taiyinZiweiCapability = 1 << 18;

/// Symbols required by the ABI-9 native baseline used by this package.
///
/// Chinese-calendar symbols and every Ganzhi entry point are always exported
/// by `taiyin_c`. The Ganzhi functions return `TAIYIN_ERROR_UNSUPPORTED` when
/// the Ganzhi extension is off, so the `ganzhiCalendar` capability tells
/// callers whether the module actually works. BaZi symbols are intentionally
/// excluded: they only exist when the library is built with
/// `TAIYIN_BUILD_BAZI_EXTENSION=ON`, so the package gates them by capability
/// instead of requiring them.
const Set<String> taiyinRequiredAbi9Symbols = {
  'taiyin_make_call_result',
  'taiyin_call_result_status',
  'taiyin_call_result_flags',
  'taiyin_call_result_ok',
  'taiyin_get_library_codename',
  'taiyin_format_ephemeris_diagnostic',
  'taiyin_register_native_position_evaluator',
  'taiyin_unregister_native_position_evaluator',
  'taiyin_clear_native_position_evaluators',
  'taiyin_runtime_add_source_path',
  'taiyin_runtime_load_eop_table',
  'taiyin_runtime_load_builtin_eop_table',
  'taiyin_runtime_clear_eop_table',
  'taiyin_runtime_has_eop_table',
  'taiyin_runtime_load_lunar_limb_model',
  'taiyin_runtime_clear_lunar_limb_model',
  'taiyin_runtime_has_lunar_limb_model',
  'taiyin_runtime_clear_ephemeris_cache',
  'taiyin_runtime_cache_entry_count',
  'taiyin_body_osculating_orbit_init',
  'taiyin_body_orbit_reference_points_init',
  'taiyin_body_apsis_search_result_init',
  'taiyin_body_node_search_result_init',
  'taiyin_calc_body_osculating_orbit_tt',
  'taiyin_calc_body_osculating_orbit_ut',
  'taiyin_calc_body_orbit_reference_points_tt',
  'taiyin_calc_body_orbit_reference_points_ut',
  'taiyin_search_next_body_apsis_tt',
  'taiyin_search_next_body_apsis_ut',
  'taiyin_search_next_body_plane_node_tt',
  'taiyin_search_next_body_plane_node_ut',
  'taiyin_body_phenomena_init',
  'taiyin_calc_body_phenomena_tt',
  'taiyin_calc_body_phenomena_ut',
  'taiyin_equation_of_time_result_init',
  'taiyin_calc_equation_of_time_ut',
  'taiyin_calc_equation_of_time_tt',
  'taiyin_local_mean_to_apparent_solar_time',
  'taiyin_local_apparent_to_mean_solar_time',
  'taiyin_star_catalog_add_tsc1',
  'taiyin_star_catalog_add_tsc1_memory',
  'taiyin_star_catalog_add_tsf1',
  'taiyin_star_catalog_clear',
  'taiyin_star_catalog_count',
  'taiyin_star_find_magnitude',
  'taiyin_calc_star_position_tdb',
  'taiyin_calc_star_position_tt',
  'taiyin_calc_star_position_ut',
  'taiyin_calc_star_position_ut_delta_t',
  'taiyin_calc_star_positions_tdb',
  'taiyin_calc_star_positions_tt',
  'taiyin_calc_star_positions_ut',
  'taiyin_calc_star_positions_ut_delta_t',
  'taiyin_calc_observed_star_ut',
  'taiyin_calc_observed_stars_ut',
  'taiyin_sidereal_position_init',
  'taiyin_sidereal_coordinates_init',
  'taiyin_house_result_init',
  'taiyin_house_position_result_init',
  'taiyin_lunar_node_position_init',
  'taiyin_lunar_apsis_position_init',
  'taiyin_calc_ayanamsha_tt',
  'taiyin_calc_sidereal_position_tt',
  'taiyin_calc_sidereal_position_ut',
  'taiyin_calc_sidereal_coordinates_tt',
  'taiyin_calc_sidereal_coordinates_ut',
  'taiyin_calc_houses_from_armc',
  'taiyin_calc_houses_ut',
  'taiyin_calc_houses_tt',
  'taiyin_calc_house_position_from_longitude',
  'taiyin_has_house_system_model',
  'taiyin_has_ayanamsha_model',
  'taiyin_register_ayanamsha_model',
  'taiyin_register_house_system_model',
  'taiyin_register_ayanamsha_model_with_token',
  'taiyin_register_house_system_model_with_token',
  'taiyin_unregister_ayanamsha_model',
  'taiyin_unregister_house_system_model',
  'taiyin_unregister_ayanamsha_model_with_token',
  'taiyin_unregister_house_system_model_with_token',
  'taiyin_clear_ayanamsha_models',
  'taiyin_clear_house_system_models',
  'taiyin_register_builtin_astrology_targets',
  'taiyin_calc_lunar_true_node_tt',
  'taiyin_calc_lunar_true_node_ut',
  'taiyin_calc_lunar_mean_node_tt',
  'taiyin_calc_lunar_mean_node_ut',
  'taiyin_calc_lunar_mean_apogee_tt',
  'taiyin_calc_lunar_mean_apogee_ut',
  'taiyin_calc_lunar_osculating_apogee_tt',
  'taiyin_calc_lunar_osculating_apogee_ut',
  'taiyin_calc_lunar_fitted_apogee_tt',
  'taiyin_calc_lunar_fitted_apogee_ut',
  'taiyin_visibility_event_result_init',
  'taiyin_solar_rise_set_fast_result_init',
  'taiyin_solar_transit_fast_result_init',
  'taiyin_search_moon_rise_set_ut',
  'taiyin_search_moon_rise_set_at_horizon_ut',
  'taiyin_search_moon_transit_ut',
  'taiyin_search_planet_rise_set_ut',
  'taiyin_search_planet_rise_set_at_horizon_ut',
  'taiyin_search_planet_transit_ut',
  'taiyin_search_solar_rise_set_ut',
  'taiyin_search_solar_rise_set_at_horizon_ut',
  'taiyin_search_solar_twilight_ut',
  'taiyin_search_solar_transit_ut',
  'taiyin_compute_solar_rise_set_fast_tt',
  'taiyin_compute_solar_transit_fast_tt',
  'taiyin_search_star_rise_set_ut',
  'taiyin_search_star_rise_set_at_horizon_ut',
  'taiyin_search_star_transit_ut',
  'taiyin_heliacal_visibility_conditions_init',
  'taiyin_heliacal_visibility_result_init',
  'taiyin_heliacal_visibility_search_result_init',
  'taiyin_calc_body_heliacal_visibility_ut',
  'taiyin_calc_star_heliacal_visibility_ut',
  'taiyin_search_next_body_heliacal_visibility_ut',
  'taiyin_search_next_star_heliacal_visibility_ut',
  'taiyin_greatest_elongation_result_init',
  'taiyin_angular_separation_result_init',
  'taiyin_solar_transit_result_init',
  'taiyin_local_solar_transit_result_init',
  'taiyin_recommended_longitude_search_step_days',
  'taiyin_recommended_aspect_search_step_days',
  'taiyin_search_solar_longitude_ut',
  'taiyin_search_solar_longitude_tt',
  'taiyin_search_moon_longitude_ut',
  'taiyin_search_moon_longitude_tt',
  'taiyin_search_body_longitude_crossings_ut',
  'taiyin_search_body_longitude_crossings_tt',
  'taiyin_search_body_longitude_stations_ut',
  'taiyin_search_body_longitude_stations_tt',
  'taiyin_search_body_aspect_crossings_ut',
  'taiyin_search_body_aspect_crossings_tt',
  'taiyin_search_body_exact_aspects_ut',
  'taiyin_search_body_exact_aspects_tt',
  'taiyin_search_greatest_elongation_ut',
  'taiyin_search_minimum_angular_separation_ut',
  'taiyin_search_minimum_angular_separation_tt',
  'taiyin_search_next_solar_transit_ut',
  'taiyin_compute_local_solar_transit_ut',
  'taiyin_search_next_local_solar_transit_ut',
  'taiyin_search_lunar_phase_crossings_ut',
  'taiyin_search_lunar_phase_crossings_tt',
  'taiyin_lunar_occultation_result_init',
  'taiyin_lunar_occultation_local_visibility_init',
  'taiyin_lunar_occultation_where_result_init',
  'taiyin_search_next_geocentric_lunar_star_occultation_ut',
  'taiyin_search_next_local_lunar_star_occultation_ut',
  'taiyin_search_next_geocentric_lunar_body_occultation_ut',
  'taiyin_search_next_geocentric_lunar_body_occultation_with_radius_ut',
  'taiyin_search_next_local_lunar_body_occultation_ut',
  'taiyin_search_next_local_lunar_body_occultation_with_radius_ut',
  'taiyin_compute_lunar_star_occultation_local_visibility_ut',
  'taiyin_compute_lunar_body_occultation_local_visibility_ut',
  'taiyin_compute_lunar_star_occultation_where_ut',
  'taiyin_compute_lunar_body_occultation_where_ut',
  'taiyin_compute_lunar_body_occultation_where_with_radius_ut',
  'taiyin_lunar_eclipse_result_tt_init',
  'taiyin_lunar_eclipse_result_ut_init',
  'taiyin_local_lunar_eclipse_result_tt_init',
  'taiyin_local_lunar_eclipse_result_ut_init',
  'taiyin_solve_lunar_eclipse_at_tt',
  'taiyin_solve_lunar_eclipse_at_ut',
  'taiyin_search_next_lunar_eclipse_tt',
  'taiyin_search_next_lunar_eclipse_ut',
  'taiyin_search_lunar_eclipses_tt',
  'taiyin_search_lunar_eclipses_ut',
  'taiyin_compute_local_lunar_eclipse_visibility_tt',
  'taiyin_compute_local_lunar_eclipse_visibility_ut',
  'taiyin_search_next_local_lunar_eclipse_tt',
  'taiyin_search_next_local_lunar_eclipse_ut',
  'taiyin_solar_eclipse_result_tt_init',
  'taiyin_solar_eclipse_result_ut_init',
  'taiyin_local_solar_eclipse_result_tt_init',
  'taiyin_local_solar_eclipse_result_ut_init',
  'taiyin_local_solar_eclipse_circumstances_tt_init',
  'taiyin_local_solar_eclipse_circumstances_ut_init',
  'taiyin_local_solar_eclipse_boundary_init',
  'taiyin_solar_besselian_elements_init',
  'taiyin_solar_besselian_polynomial_init',
  'taiyin_solar_eclipse_route_row_init',
  'taiyin_solar_eclipse_route_product_summary_init',
  'taiyin_solve_solar_eclipse_at_tt',
  'taiyin_solve_solar_eclipse_at_ut',
  'taiyin_search_next_solar_eclipse_tt',
  'taiyin_search_next_solar_eclipse_ut',
  'taiyin_search_solar_eclipses_tt',
  'taiyin_search_solar_eclipses_ut',
  'taiyin_solve_local_solar_eclipse_at_tt',
  'taiyin_solve_local_solar_eclipse_at_ut',
  'taiyin_search_next_local_solar_eclipse_tt',
  'taiyin_search_next_local_solar_eclipse_ut',
  'taiyin_compute_local_solar_circumstances_tt',
  'taiyin_compute_local_solar_circumstances_ut',
  'taiyin_compute_solar_besselian_elements_tt',
  'taiyin_compute_solar_besselian_polynomial_tt',
  'taiyin_evaluate_solar_besselian_polynomial',
  'taiyin_compute_solar_eclipse_route_row_tt',
  'taiyin_compute_solar_eclipse_route_row_ut',
  'taiyin_compute_solar_eclipse_route_tt',
  'taiyin_compute_solar_eclipse_route_ut',
  'taiyin_compute_solar_eclipse_route_curves_tt',
  'taiyin_compute_solar_eclipse_route_curves_ut',
  'taiyin_compute_solar_eclipse_route_product_tt',
  'taiyin_compute_solar_eclipse_route_product_ut',
  'taiyin_compute_solar_eclipse_route_map_product_tt',
  'taiyin_compute_solar_eclipse_route_map_product_ut',
  'taiyin_compute_local_solar_eclipse_boundary_tt',
  'taiyin_compute_local_solar_eclipse_boundary_ut',
  'taiyin_chinese_calendar_config_init',
  'taiyin_solar_date_init',
  'taiyin_lunar_date_init',
  'taiyin_chinese_solar_term_event_init',
  'taiyin_chinese_calendar_year_init',
  'taiyin_chinese_calendar_context_create',
  'taiyin_chinese_calendar_context_destroy',
  'taiyin_chinese_calendar_calc_year_ut',
  'taiyin_chinese_calendar_get_specific_jie_qi_ut',
  'taiyin_chinese_calendar_get_prev_jie_qi_ut',
  'taiyin_chinese_calendar_get_next_jie_qi_ut',
  'taiyin_chinese_calendar_get_prev_jie_ut',
  'taiyin_chinese_calendar_get_next_jie_ut',
  'taiyin_chinese_calendar_get_prev_qi_ut',
  'taiyin_chinese_calendar_get_next_qi_ut',
  'taiyin_chinese_calendar_from_solar',
  'taiyin_chinese_calendar_from_instant_ut',
  'taiyin_chinese_calendar_from_lunar',
  'taiyin_chinese_calendar_get_month_days',
  'taiyin_ganzhi_four_pillars_init',
  'taiyin_ganzhi_make',
  'taiyin_ganzhi_advance',
  'taiyin_ganzhi_get_month',
  'taiyin_ganzhi_get_hour',
  'taiyin_ganzhi_get_nayin_element',
  'taiyin_ganzhi_get_nayin_id',
  'taiyin_ganzhi_calc_day_pillar',
  'taiyin_chinese_calendar_calc_four_pillars_ut',
};

/// BaZi symbols, verified by `package:taiyin_bazi` only when the loaded
/// library advertises the BaZi capability. The symbols do not exist in a build
/// without `TAIYIN_BUILD_BAZI_EXTENSION=ON`, so they must never be looked up
/// otherwise.
const Set<String> taiyinBaziSymbols = {
  'taiyin_bazi_context_config_init',
  'taiyin_bazi_chart_init',
  'taiyin_bazi_relation_init',
  'taiyin_bazi_qiyun_result_init',
  'taiyin_bazi_dayun_init',
  'taiyin_bazi_xiaoyun_init',
  'taiyin_bazi_renyuan_siling_segment_init',
  'taiyin_bazi_renyuan_siling_result_init',
  'taiyin_bazi_context_create',
  'taiyin_bazi_context_destroy',
  'taiyin_bazi_get_kong_wang',
  'taiyin_bazi_get_ten_god',
  'taiyin_bazi_get_hidden_stems',
  'taiyin_bazi_calc_stem_relation',
  'taiyin_bazi_calc_branch_relation',
  'taiyin_bazi_calc_branch_triple_relation',
  'taiyin_bazi_get_life_stage',
  'taiyin_bazi_calc_chart',
  'taiyin_bazi_calc_liunian',
  'taiyin_bazi_calc_liuyue',
  'taiyin_bazi_calc_liuri',
  'taiyin_bazi_calc_liushi',
  'taiyin_bazi_calc_xiaoyun',
  'taiyin_bazi_fill_xiaoyun',
  'taiyin_bazi_collect_chart_relations',
  'taiyin_bazi_collect_target_shen_sha',
  'taiyin_bazi_collect_target_shen_sha_with_gender',
  'taiyin_bazi_calc_qiyun',
  'taiyin_bazi_fill_dayun',
  'taiyin_bazi_get_renyuan_siling_segments',
  'taiyin_bazi_calc_renyuan_siling',
};

/// Ziwei symbols, verified only when the loaded library advertises the Ziwei
/// capability. The symbols do not exist in a build without
/// `TAIYIN_BUILD_ZIWEI_EXTENSION=ON`, so they must never be looked up
/// otherwise.
const Set<String> taiyinZiweiSymbols = {
  'taiyin_ziwei_option_override_init',
  'taiyin_ziwei_birth_options_init',
  'taiyin_ziwei_flow_options_init',
  'taiyin_ziwei_transform_set_init',
  'taiyin_ziwei_flow_summary_init',
  'taiyin_ziwei_reverse_query_init',
  'taiyin_ziwei_reverse_request_init',
  'taiyin_ziwei_reverse_candidate_init',
  'taiyin_ziwei_data_catalog_create',
  'taiyin_ziwei_data_catalog_destroy',
  'taiyin_ziwei_data_catalog_reload',
  'taiyin_ziwei_data_catalog_generation',
  'taiyin_ziwei_context_create',
  'taiyin_ziwei_context_destroy',
  'taiyin_ziwei_context_generation',
  'taiyin_ziwei_star_count',
  'taiyin_ziwei_find_star',
  'taiyin_ziwei_get_star_metadata',
  'taiyin_ziwei_chart_create',
  'taiyin_ziwei_chart_destroy',
  'taiyin_ziwei_reverse_lookup_tier1',
  'taiyin_ziwei_chart_get_anchors',
  'taiyin_ziwei_chart_get_summary',
  'taiyin_ziwei_chart_get_palace_branch',
  'taiyin_ziwei_chart_get_palace_stem',
  'taiyin_ziwei_chart_get_star_position',
  'taiyin_ziwei_chart_get_star_palace',
  'taiyin_ziwei_chart_get_brightness',
  'taiyin_ziwei_chart_has_star_transform_mark',
  'taiyin_ziwei_chart_get_star_transformation_mask',
  'taiyin_ziwei_chart_get_palace_stars',
  'taiyin_ziwei_chart_set_flow',
  'taiyin_ziwei_chart_truncate_flow',
  'taiyin_ziwei_chart_flow_layer_count',
  'taiyin_ziwei_chart_get_flow_star_position',
  'taiyin_ziwei_chart_get_flow_layer_summary',
  'taiyin_ziwei_chart_get_flow_palace_stars',
  'taiyin_ziwei_chart_get_flow_transforms',
  'taiyin_ziwei_step_flow_hour_target',
  'taiyin_ziwei_step_flow_day_target',
};

/// Validates the native metadata available before any optional symbol lookup.
///
/// This stays independent of generated bindings so compatibility behavior can
/// be tested without loading a platform-specific dynamic library.
///
/// The Dart package exposes its split-date time service and its Chinese
/// calendar and Ganzhi services as required parts of every
/// `EphemerisContext`, so it requires split-time and Chinese-calendar support.
/// BaZi and Ziwei validate their separately loaded native modules instead of
/// consulting the core capability mask.
void validateTaiyinNativeCompatibility({
  required int abiVersion,
  required int capabilities,
}) {
  if (abiVersion != taiyinSupportedAbiVersion) {
    throw StateError(
      'Unsupported Taiyin C ABI $abiVersion; '
      'this package supports ABI $taiyinSupportedAbiVersion.',
    );
  }
  if ((capabilities & taiyinSplitTimeCapability) == 0) {
    throw StateError(
      'The loaded Taiyin library does not provide the split-time capability '
      'required by this package.',
    );
  }
  if ((capabilities & taiyinChineseCalendarCapability) == 0) {
    throw StateError(
      'The loaded Taiyin library does not provide the Chinese-calendar '
      'capability required by this package.',
    );
  }
}

/// Rejects incomplete ABI-9 builds before generated bindings lazily look up a
/// missing symbol.
void validateTaiyinRequiredSymbols({
  required bool Function(String symbol) providesSymbol,
  Set<String> requiredSymbols = taiyinRequiredAbi9Symbols,
}) {
  final missing = [
    for (final symbol in requiredSymbols)
      if (!providesSymbol(symbol)) symbol,
  ];
  if (missing.isNotEmpty) {
    throw StateError(
      'The loaded Ephemeris ABI-9 library is missing symbols required by this '
      'package: ${missing.join(', ')}. Rebuild or update the native library.',
    );
  }
}
